"""Stable public contracts for MarkItDown 2Ways.

Phase A intentionally keeps registry mechanics and format implementations out of
this root namespace. Import `markitdown.twoways._registry` only from internal
facades/format adapters that need registration behavior.
"""

from ._errors import (
    AmbiguousNativeLocatorError,
    IRValidationError,
    MarkdownIdentityError,
    MarkdownImportError,
    MarkdownProjectionError,
    MarkdownSemanticParseError,
    MissingOptionalDependencyError,
    OOXMLPackageError,
    PatchPreconditionError,
    ReaderNotFoundError,
    RoundTripVerificationError,
    SourcePackageMismatchError,
    TwoWayError,
    UnsupportedEditError,
    UnsupportedSchemaVersionError,
    WriterNotFoundError,
)
from ._results import FidelityEvidence, FidelityReport, FidelityStatus, WriterResult
from .capabilities import (
    CapabilityDecision,
    CapabilityReasonSummary,
    CapabilityReport,
    CapabilityState,
    NodeCapabilityProfile,
    build_capability_report,
    capabilities_for_node,
)
from .ir import (
    BoundingBox,
    Canvas,
    ChartPayload,
    Diagnostic,
    DocumentIdFactory,
    DocumentIR,
    DocumentMetadata,
    EditOperation,
    EditPrecondition,
    Geometry,
    ImagePayload,
    NativeLocator,
    NativePayload,
    Node,
    Paragraph,
    Provenance,
    Relationship,
    Resource,
    SourceDescriptor,
    Style,
    TableCell,
    TablePayload,
    TextPayload,
    TextRun,
    UnknownNativePayload,
)
from .ir.serialization import (
    canonical_json_bytes,
    canonical_json_digest,
    decode_document,
    to_canonical_dict,
    validate_document,
)

from .markdown import (
    MarkdownImportResult,
    MarkdownProjection,
    MarkdownProjectionMode,
    MarkdownProjectionOptions,
    ProjectionManifest,
    import_identity_markdown,
    project_markdown,
    projection_manifest_bytes,
    projection_manifest_digest,
    read_markdown_ir,
)

from .readers import DocumentIRReader
from .writers import DocumentWriter, TargetInfo

__all__ = [
    "AmbiguousNativeLocatorError",
    "BoundingBox",
    "Canvas",
    "CapabilityDecision",
    "CapabilityReasonSummary",
    "CapabilityReport",
    "CapabilityState",
    "ChartPayload",
    "Diagnostic",
    "DocumentIdFactory",
    "DocumentIR",
    "DocumentIRReader",
    "DocumentMetadata",
    "DocumentWriter",
    "EditOperation",
    "EditPrecondition",
    "FidelityEvidence",
    "FidelityReport",
    "FidelityStatus",
    "Geometry",
    "IRValidationError",
    "MarkdownIdentityError",
    "MarkdownImportError",
    "MarkdownProjectionError",
    "MarkdownSemanticParseError",
    "MissingOptionalDependencyError",
    "OOXMLPackageError",
    "ImagePayload",
    "NativeLocator",
    "NativePayload",
    "Node",
    "NodeCapabilityProfile",
    "Paragraph",
    "PatchPreconditionError",
    "Provenance",
    "ReaderNotFoundError",
    "Relationship",
    "Resource",
    "RoundTripVerificationError",
    "SourceDescriptor",
    "SourcePackageMismatchError",
    "Style",
    "TableCell",
    "TablePayload",
    "TargetInfo",
    "TextPayload",
    "TextRun",
    "TwoWayError",
    "UnknownNativePayload",
    "UnsupportedEditError",
    "UnsupportedSchemaVersionError",
    "WriterNotFoundError",
    "WriterResult",
    "build_capability_report",
    "capabilities_for_node",
    "read_markdown_ir",
    "projection_manifest_digest",
    "projection_manifest_bytes",
    "project_markdown",
    "import_identity_markdown",
    "ProjectionManifest",
    "MarkdownProjectionOptions",
    "MarkdownProjectionMode",
    "MarkdownProjection",
    "MarkdownImportResult",
    "canonical_json_bytes",
    "canonical_json_digest",
    "decode_document",
    "to_canonical_dict",
    "validate_document",
]
